
#ifndef REPLACE_WITH_YOUR_PROJECT_NAME_ELEMENT_HPP
#define REPLACE_WITH_YOUR_PROJECT_NAME_ELEMENT_HPP

enum class Element {
    NEUTRAL,
    FIRE,
    WATER,
    TOXIC,
    ICE
};

#endif //REPLACE_WITH_YOUR_PROJECT_NAME_ELEMENT_HPP